######################################################################
# Automatically generated by qmake (3.0) ?? 1? 28 21:23:50 2017
######################################################################

TEMPLATE = app
TARGET = CMCL
INCLUDEPATH += .

# Input
SOURCES += main.cpp

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++14
